### ISSUE TITLE
InfoOnly:  Got your code working on a Teensy 3.5

### ISSUE THREAD

**Issue by mjs513** [getSurreal/XV_Lidar_Controller#4]
Just thought I would let you know that your code (at least the branch with 3.1 in it already) will work with a Teensy 3.5.  The only problem I had was on initialization of the eeprom - would always default to pwm pin of 14 even after the ifdefs.  If you hard code it in the setup it works fine.

THought you would like to know.  Still have more work to do on it.
Mike

**Comment by getSurreal** [comment]
Great to know!  

As for pwm pin not saving make sure that these two values match and/or increment them any time you change the defaults.

```
const byte EEPROM_ID = 0x06;
xv_config.id = 0x06;
```

The Teensy 3.5 will need a new section like below, but that's just to make the same code compatible for multiple boards.  In your case, hard coding it is fine.

```
#elif defined(__MK20DX256__)  // if Teensy 3.1
  xv_config.motor_pwm_pin = 33;  // pin connected N-Channel Mosfet
#endif
```

**Comment by mjs513** [comment]
I had did that but I didn't increment the EEPROM_ID.  Once I did that it worked.  Not sure how to do a push but I am attaching it in a zip file.  I also updated the new TimerThree library,

Mike
[XV_Lidar_Controller.zip](https://github.com/getSurreal/XV_Lidar_Controller/files/607744/XV_Lidar_Controller.zip)

**Comment by getSurreal** [comment]
Thanks!  I'll add the updates for Teensy 3.5 with the next release.  

BTW, if you don't keep these two the same, you'll be rewriting your EEPROM everytime it boots.  In other words they both need to be incremented when making a change to any EEPROM settings.

```
const byte EEPROM_ID = 0x06;
xv_config.id = 0x06;
```

**Comment by mjs513** [comment]
Thanks.  Just took care of that.  I do have another question, don't know if you want me to open an another issue though.  I been playing with your code and trying to get it to work in a polling type of mode.  In other words read the sensor every second for example and load the distance data into an array but I am not having much luck with it.  Think I need to read up on how the packets are sent.  Any suggestions would be helpful.

Thanks
Mike

**Comment by getSurreal** [comment]
Look for the section that prints the ascii angle information and add you code to write to the array. 

I would suggest to not change the reading of the data because it's also using that to maintain the RPMs. Instead just update your array at the interval you want. 

Hope that helps.

**Comment by mjs513** [comment]
Thanks a bunch. Got it working the way I want. Putting the data into an array and printing out after the last packet is received. Also works now wot set angle. Using Paul S elapsed Millis lib do the job.

Now the fun stuff starts with incorporating the bubble algorithm I am using for obstacle avoidance.

Thanks a bunch for help. 
Mike

Ps. Have ever thought about offering a board that just brings the pins (pwr. Gnd, pwm, tx) so you can use it with other boards?

**Comment by wadcock2** [comment]
This will work on Teensy 3.6 too, right?



-----Original Message-----

**Comment by mjs513** [comment]
Teensy 3.6 is 3.3v and the pins aren't 5v tolerate. You will have to be careful with power and m and maybe pwm and rx. Not sure. The 3.5 is 3.3v but the pins are 5v tolerant.  I have a 3.6 but haven't t r oed it. The code should work once you verify the power. You can also post the question on the prjc forum.  Or maybe the guys at getsurreal would know for sure.

**Comment by getSurreal** [comment]
Mike is correct.  The code should work, but you have to be mindful of 
the voltage.

**Comment by mjs513** [comment]
Me again.  Have another question for you if you don't mind.  Got everything working but now I need to programmatically set the angle ranges.  Is there an easy way to do that?  

thanks
Mike
