### ISSUE TITLE
Timer3 no longer working on T3.x

### ISSUE THREAD

**Issue by mjs513** [getSurreal/XV_Lidar_Controller#5]
Getting back into this with the advent of the Teensy 4 and decided to retest with the T3.2.  Ran into one problem since I originally tested is that TImerThree no longer drives the pwm signal for the motor of the XV-11.  I am using v1.2 of your breakout though - it did use to work back in 2016.

I replaced Timer2.pwm with analogWrite's and it started working without a problem.  Once I did this it even worked on the new T4.

Only other problem I am getting a bunch of errors mostly "I" - invalid data if too close - like a couple hundred mm's and some "S" signal strength.  Any suggestions

**Comment by getSurreal** [comment]
Timer3 should still work.  Double check which pins on the board work with Timer 3 and define it in this section.

```
#if defined(__AVR_ATmega32U4__) && defined(CORE_TEENSY)  // if Teensy 2.0
  xv_config.motor_pwm_pin = 9;  // pin connected N-Channel Mosfet

#elif defined(__AVR_ATmega32U4__)  // if Leonardo or Pro Micro
  xv_config.motor_pwm_pin = 5;  // pin connected N-Channel Mosfet

#elif defined(__MK20DX256__)  // if Teensy 3.1
  xv_config.motor_pwm_pin = 33;  // pin connected N-Channel Mosfet

#elif defined(__MKL26Z64__)  // if Teensy LC
  xv_config.motor_pwm_pin = 4;  // pin connected N-Channel Mosfet
#endif
```

**Comment by getSurreal** [comment]
Minimum distance is 150mm.  If you're over 200mm from an object, it should be good enough.  I find that when your trying to do that kind of troubleshooting, it's helpful to use the serial commands to limit the output of angles to just one and use a white piece of paper over the side of a box for a controlled environment.

**Comment by mjs513** [comment]
Thanks - did a double check of the pins that can be used.  For TimerThree only pins 25 and 32 can be used which are on the underside of the T3.2.  On the other hand TImerOne uses pins 3 and 4 can be used.  So since I didn't want to solder underside pins I changed it to use TimerOne and used pin 3.  This resolved the problem - you may want to consider changing to TimerOne in the code as opposed to pin 33 which is incorrect as well.  Just thought you should know about that one.

Thanks on the minimum distance - you are probably right - should put in a box for a test.
